## 문제주소

> https://www.acmicpc.net/problem/1676

</br>

### 트러블 슈팅

RecursionError 런타임 에러가 났다.  
찾아보니 RecursionError는 재귀와 관련된 에러라고 한다. 이것이 가장 많이 발생하는 이유는 python이 정한 최대 재귀 깊이보다 재귀의 깊이가 더 길어질때라고 한다.  
python이 정한 최대 재귀 깊이는 `sys.getrecursionlimit()`이용해 알 수 있다. BOJ의 채점 서버에는 이 값은 1000으로 되어있다.

```py
def calc(n):
    if n == 0:
        return 0
    else:
        return n + calc(n-1)

n = int(input())
print(calc(n))
```

위의 코드에서 calc(n)을 호출하면 총 n+1번의 재귀 호출이 발생한다. print(calc(n))으로 호출하고 있기 때문에, print(calc(n))의 재귀의 깊이는 n+2가 된다.  
따라서 n<998 의 경우에는 RecursionError가 발생하지 않지만 n >= 998 부터는 에러가 발생하게 됩니다.

해당 에러를 해결하는 방법은 두가지가 있다.

1. 재귀 함수를 사용하지 않는 것.

```py
def calc(n):
    ans = 0
    for i in range(1, n+1):
        ans += i
    return ans

n = int(input())
print(calc(n))
```

2. `sys.setrecursionlimit()`을 사용
   이 함수를 사용하면 python이 정한 최대 재귀 깊이를 변경할 수 있다.  
   최대 재귀 깊이를 1,000,000 정도로 크게 ㅓ설정하면 런타임 에러 없이 실행이 된다.

```py
import sys
sys.setrecursionlimit(10**6)
def calc(n):
    if n == 0:
        return 0
    else:
        return n + calc(n-1)

n = int(input())
print(calc(n))
```

해당 값을 설정한다고 하여도 재귀의 깊이가 채점 서버가 감당할 수 없을 정도로 깊어지면 `Segmentation fault`가 발생해 런타입 에러가 생김.

위의 문제에서는 N이 500의 경우 500!는 int의 범위인 21억을 초과하게 된다.

## 내가 푼 코드

```py
import sys

N = int(input())
count = 0
sum = 1
sys.setrecursionlimit(10**6)
def factorial(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    return n * factorial(n-1)


numList = str(factorial(N))

for i in range(len(numList)-1,0,-1):
    if numList[i] != '0':
        break
    count+=1


print(count)
```

기존 코드에서 sys.setrecursionlimit(10\*\*6)만 추가하여 제출했더니 맞출 수 있었다.
